// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cardchain/cardchain/council.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cardchain.Cardchain {

  /// <summary>Holder for reflection information generated from cardchain/cardchain/council.proto</summary>
  public static partial class CouncilReflection {

    #region Descriptor
    /// <summary>File descriptor for cardchain/cardchain/council.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CouncilReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFjYXJkY2hhaW4vY2FyZGNoYWluL2NvdW5jaWwucHJvdG8SE2NhcmRjaGFp",
            "bi5jYXJkY2hhaW4aFGdvZ29wcm90by9nb2dvLnByb3RvGh5jb3Ntb3MvYmFz",
            "ZS92MWJldGExL2NvaW4ucHJvdG8i8gIKB0NvdW5jaWwSFgoGY2FyZElkGAEg",
            "ASgEUgZjYXJkSWQSFgoGdm90ZXJzGAIgAygJUgZ2b3RlcnMSSwoNaGFzaFJl",
            "c3BvbnNlcxgDIAMoCzIlLmNhcmRjaGFpbi5jYXJkY2hhaW4uV3JhcEhhc2hS",
            "ZXNwb25zZVINaGFzaFJlc3BvbnNlcxJOCg5jbGVhclJlc3BvbnNlcxgEIAMo",
            "CzImLmNhcmRjaGFpbi5jYXJkY2hhaW4uV3JhcENsZWFyUmVzcG9uc2VSDmNs",
            "ZWFyUmVzcG9uc2VzEjsKCHRyZWFzdXJ5GAggASgLMhkuY29zbW9zLmJhc2Uu",
            "djFiZXRhMS5Db2luQgTI3h8AUgh0cmVhc3VyeRI9CgZzdGF0dXMYBiABKA4y",
            "JS5jYXJkY2hhaW4uY2FyZGNoYWluLkNvdW5jZWxpbmdTdGF0dXNSBnN0YXR1",
            "cxIeCgp0cmlhbFN0YXJ0GAcgASgEUgp0cmlhbFN0YXJ0IoIBChFXcmFwQ2xl",
            "YXJSZXNwb25zZRISCgR1c2VyGAEgASgJUgR1c2VyEjkKCHJlc3BvbnNlGAIg",
            "ASgOMh0uY2FyZGNoYWluLmNhcmRjaGFpbi5SZXNwb25zZVIIcmVzcG9uc2US",
            "HgoKc3VnZ2VzdGlvbhgDIAEoCVIKc3VnZ2VzdGlvbiI6ChBXcmFwSGFzaFJl",
            "c3BvbnNlEhIKBHVzZXIYASABKAlSBHVzZXISEgoEaGFzaBgCIAEoCVIEaGFz",
            "aCorCghSZXNwb25zZRIHCgNZZXMQABIGCgJObxABEg4KClN1Z2dlc3Rpb24Q",
            "Aip7ChBDb3VuY2VsaW5nU3RhdHVzEg8KC2NvdW5jaWxPcGVuEAASEgoOY291",
            "bmNpbENyZWF0ZWQQARIRCg1jb3VuY2lsQ2xvc2VkEAISDAoIY29tbWl0ZWQQ",
            "AxIMCghyZXZlYWxlZBAEEhMKD3N1Z2dlc3Rpb25zTWFkZRAFQtABChdjb20u",
            "Y2FyZGNoYWluLmNhcmRjaGFpbkIMQ291bmNpbFByb3RvUAFaOmdpdGh1Yi5j",
            "b20vRGVjZW50cmFsQ2FyZGdhbWUvY2FyZGNoYWluL2NhcmRjaGFpbi9jYXJk",
            "Y2hhaW6iAgNDQ1iqAhNDYXJkY2hhaW4uQ2FyZGNoYWluygITQ2FyZGNoYWlu",
            "XENhcmRjaGFpbuICH0NhcmRjaGFpblxDYXJkY2hhaW5cR1BCTWV0YWRhdGHq",
            "AhRDYXJkY2hhaW46OkNhcmRjaGFpbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gogoproto.GogoReflection.Descriptor, global::Cosmos.Base.V1beta1.CoinReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Cardchain.Cardchain.Response), typeof(global::Cardchain.Cardchain.CouncelingStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Cardchain.Cardchain.Council), global::Cardchain.Cardchain.Council.Parser, new[]{ "CardId", "Voters", "HashResponses", "ClearResponses", "Treasury", "Status", "TrialStart" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cardchain.Cardchain.WrapClearResponse), global::Cardchain.Cardchain.WrapClearResponse.Parser, new[]{ "User", "Response", "Suggestion" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cardchain.Cardchain.WrapHashResponse), global::Cardchain.Cardchain.WrapHashResponse.Parser, new[]{ "User", "Hash" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Response {
    [pbr::OriginalName("Yes")] Yes = 0,
    [pbr::OriginalName("No")] No = 1,
    [pbr::OriginalName("Suggestion")] Suggestion = 2,
  }

  public enum CouncelingStatus {
    [pbr::OriginalName("councilOpen")] CouncilOpen = 0,
    [pbr::OriginalName("councilCreated")] CouncilCreated = 1,
    [pbr::OriginalName("councilClosed")] CouncilClosed = 2,
    [pbr::OriginalName("commited")] Commited = 3,
    [pbr::OriginalName("revealed")] Revealed = 4,
    [pbr::OriginalName("suggestionsMade")] SuggestionsMade = 5,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Council : pb::IMessage<Council>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Council> _parser = new pb::MessageParser<Council>(() => new Council());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Council> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cardchain.Cardchain.CouncilReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Council() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Council(Council other) : this() {
      cardId_ = other.cardId_;
      voters_ = other.voters_.Clone();
      hashResponses_ = other.hashResponses_.Clone();
      clearResponses_ = other.clearResponses_.Clone();
      treasury_ = other.treasury_ != null ? other.treasury_.Clone() : null;
      status_ = other.status_;
      trialStart_ = other.trialStart_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Council Clone() {
      return new Council(this);
    }

    /// <summary>Field number for the "cardId" field.</summary>
    public const int CardIdFieldNumber = 1;
    private ulong cardId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CardId {
      get { return cardId_; }
      set {
        cardId_ = value;
      }
    }

    /// <summary>Field number for the "voters" field.</summary>
    public const int VotersFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_voters_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> voters_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Voters {
      get { return voters_; }
    }

    /// <summary>Field number for the "hashResponses" field.</summary>
    public const int HashResponsesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Cardchain.Cardchain.WrapHashResponse> _repeated_hashResponses_codec
        = pb::FieldCodec.ForMessage(26, global::Cardchain.Cardchain.WrapHashResponse.Parser);
    private readonly pbc::RepeatedField<global::Cardchain.Cardchain.WrapHashResponse> hashResponses_ = new pbc::RepeatedField<global::Cardchain.Cardchain.WrapHashResponse>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Cardchain.Cardchain.WrapHashResponse> HashResponses {
      get { return hashResponses_; }
    }

    /// <summary>Field number for the "clearResponses" field.</summary>
    public const int ClearResponsesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Cardchain.Cardchain.WrapClearResponse> _repeated_clearResponses_codec
        = pb::FieldCodec.ForMessage(34, global::Cardchain.Cardchain.WrapClearResponse.Parser);
    private readonly pbc::RepeatedField<global::Cardchain.Cardchain.WrapClearResponse> clearResponses_ = new pbc::RepeatedField<global::Cardchain.Cardchain.WrapClearResponse>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Cardchain.Cardchain.WrapClearResponse> ClearResponses {
      get { return clearResponses_; }
    }

    /// <summary>Field number for the "treasury" field.</summary>
    public const int TreasuryFieldNumber = 8;
    private global::Cosmos.Base.V1beta1.Coin treasury_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cosmos.Base.V1beta1.Coin Treasury {
      get { return treasury_; }
      set {
        treasury_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 6;
    private global::Cardchain.Cardchain.CouncelingStatus status_ = global::Cardchain.Cardchain.CouncelingStatus.CouncilOpen;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cardchain.Cardchain.CouncelingStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "trialStart" field.</summary>
    public const int TrialStartFieldNumber = 7;
    private ulong trialStart_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TrialStart {
      get { return trialStart_; }
      set {
        trialStart_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Council);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Council other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CardId != other.CardId) return false;
      if(!voters_.Equals(other.voters_)) return false;
      if(!hashResponses_.Equals(other.hashResponses_)) return false;
      if(!clearResponses_.Equals(other.clearResponses_)) return false;
      if (!object.Equals(Treasury, other.Treasury)) return false;
      if (Status != other.Status) return false;
      if (TrialStart != other.TrialStart) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CardId != 0UL) hash ^= CardId.GetHashCode();
      hash ^= voters_.GetHashCode();
      hash ^= hashResponses_.GetHashCode();
      hash ^= clearResponses_.GetHashCode();
      if (treasury_ != null) hash ^= Treasury.GetHashCode();
      if (Status != global::Cardchain.Cardchain.CouncelingStatus.CouncilOpen) hash ^= Status.GetHashCode();
      if (TrialStart != 0UL) hash ^= TrialStart.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CardId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(CardId);
      }
      voters_.WriteTo(output, _repeated_voters_codec);
      hashResponses_.WriteTo(output, _repeated_hashResponses_codec);
      clearResponses_.WriteTo(output, _repeated_clearResponses_codec);
      if (Status != global::Cardchain.Cardchain.CouncelingStatus.CouncilOpen) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Status);
      }
      if (TrialStart != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(TrialStart);
      }
      if (treasury_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Treasury);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CardId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(CardId);
      }
      voters_.WriteTo(ref output, _repeated_voters_codec);
      hashResponses_.WriteTo(ref output, _repeated_hashResponses_codec);
      clearResponses_.WriteTo(ref output, _repeated_clearResponses_codec);
      if (Status != global::Cardchain.Cardchain.CouncelingStatus.CouncilOpen) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Status);
      }
      if (TrialStart != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(TrialStart);
      }
      if (treasury_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Treasury);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CardId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CardId);
      }
      size += voters_.CalculateSize(_repeated_voters_codec);
      size += hashResponses_.CalculateSize(_repeated_hashResponses_codec);
      size += clearResponses_.CalculateSize(_repeated_clearResponses_codec);
      if (treasury_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Treasury);
      }
      if (Status != global::Cardchain.Cardchain.CouncelingStatus.CouncilOpen) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (TrialStart != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TrialStart);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Council other) {
      if (other == null) {
        return;
      }
      if (other.CardId != 0UL) {
        CardId = other.CardId;
      }
      voters_.Add(other.voters_);
      hashResponses_.Add(other.hashResponses_);
      clearResponses_.Add(other.clearResponses_);
      if (other.treasury_ != null) {
        if (treasury_ == null) {
          Treasury = new global::Cosmos.Base.V1beta1.Coin();
        }
        Treasury.MergeFrom(other.Treasury);
      }
      if (other.Status != global::Cardchain.Cardchain.CouncelingStatus.CouncilOpen) {
        Status = other.Status;
      }
      if (other.TrialStart != 0UL) {
        TrialStart = other.TrialStart;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CardId = input.ReadUInt64();
            break;
          }
          case 18: {
            voters_.AddEntriesFrom(input, _repeated_voters_codec);
            break;
          }
          case 26: {
            hashResponses_.AddEntriesFrom(input, _repeated_hashResponses_codec);
            break;
          }
          case 34: {
            clearResponses_.AddEntriesFrom(input, _repeated_clearResponses_codec);
            break;
          }
          case 48: {
            Status = (global::Cardchain.Cardchain.CouncelingStatus) input.ReadEnum();
            break;
          }
          case 56: {
            TrialStart = input.ReadUInt64();
            break;
          }
          case 66: {
            if (treasury_ == null) {
              Treasury = new global::Cosmos.Base.V1beta1.Coin();
            }
            input.ReadMessage(Treasury);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CardId = input.ReadUInt64();
            break;
          }
          case 18: {
            voters_.AddEntriesFrom(ref input, _repeated_voters_codec);
            break;
          }
          case 26: {
            hashResponses_.AddEntriesFrom(ref input, _repeated_hashResponses_codec);
            break;
          }
          case 34: {
            clearResponses_.AddEntriesFrom(ref input, _repeated_clearResponses_codec);
            break;
          }
          case 48: {
            Status = (global::Cardchain.Cardchain.CouncelingStatus) input.ReadEnum();
            break;
          }
          case 56: {
            TrialStart = input.ReadUInt64();
            break;
          }
          case 66: {
            if (treasury_ == null) {
              Treasury = new global::Cosmos.Base.V1beta1.Coin();
            }
            input.ReadMessage(Treasury);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WrapClearResponse : pb::IMessage<WrapClearResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WrapClearResponse> _parser = new pb::MessageParser<WrapClearResponse>(() => new WrapClearResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WrapClearResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cardchain.Cardchain.CouncilReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WrapClearResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WrapClearResponse(WrapClearResponse other) : this() {
      user_ = other.user_;
      response_ = other.response_;
      suggestion_ = other.suggestion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WrapClearResponse Clone() {
      return new WrapClearResponse(this);
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 1;
    private string user_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string User {
      get { return user_; }
      set {
        user_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 2;
    private global::Cardchain.Cardchain.Response response_ = global::Cardchain.Cardchain.Response.Yes;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cardchain.Cardchain.Response Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    /// <summary>Field number for the "suggestion" field.</summary>
    public const int SuggestionFieldNumber = 3;
    private string suggestion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Suggestion {
      get { return suggestion_; }
      set {
        suggestion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WrapClearResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WrapClearResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (User != other.User) return false;
      if (Response != other.Response) return false;
      if (Suggestion != other.Suggestion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (User.Length != 0) hash ^= User.GetHashCode();
      if (Response != global::Cardchain.Cardchain.Response.Yes) hash ^= Response.GetHashCode();
      if (Suggestion.Length != 0) hash ^= Suggestion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (User.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(User);
      }
      if (Response != global::Cardchain.Cardchain.Response.Yes) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Response);
      }
      if (Suggestion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Suggestion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (User.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(User);
      }
      if (Response != global::Cardchain.Cardchain.Response.Yes) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Response);
      }
      if (Suggestion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Suggestion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (User.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(User);
      }
      if (Response != global::Cardchain.Cardchain.Response.Yes) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Response);
      }
      if (Suggestion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Suggestion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WrapClearResponse other) {
      if (other == null) {
        return;
      }
      if (other.User.Length != 0) {
        User = other.User;
      }
      if (other.Response != global::Cardchain.Cardchain.Response.Yes) {
        Response = other.Response;
      }
      if (other.Suggestion.Length != 0) {
        Suggestion = other.Suggestion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            User = input.ReadString();
            break;
          }
          case 16: {
            Response = (global::Cardchain.Cardchain.Response) input.ReadEnum();
            break;
          }
          case 26: {
            Suggestion = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            User = input.ReadString();
            break;
          }
          case 16: {
            Response = (global::Cardchain.Cardchain.Response) input.ReadEnum();
            break;
          }
          case 26: {
            Suggestion = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WrapHashResponse : pb::IMessage<WrapHashResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WrapHashResponse> _parser = new pb::MessageParser<WrapHashResponse>(() => new WrapHashResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WrapHashResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cardchain.Cardchain.CouncilReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WrapHashResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WrapHashResponse(WrapHashResponse other) : this() {
      user_ = other.user_;
      hash_ = other.hash_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WrapHashResponse Clone() {
      return new WrapHashResponse(this);
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 1;
    private string user_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string User {
      get { return user_; }
      set {
        user_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hash" field.</summary>
    public const int HashFieldNumber = 2;
    private string hash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Hash {
      get { return hash_; }
      set {
        hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WrapHashResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WrapHashResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (User != other.User) return false;
      if (Hash != other.Hash) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (User.Length != 0) hash ^= User.GetHashCode();
      if (Hash.Length != 0) hash ^= Hash.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (User.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(User);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Hash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (User.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(User);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Hash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (User.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(User);
      }
      if (Hash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Hash);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WrapHashResponse other) {
      if (other == null) {
        return;
      }
      if (other.User.Length != 0) {
        User = other.User;
      }
      if (other.Hash.Length != 0) {
        Hash = other.Hash;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            User = input.ReadString();
            break;
          }
          case 18: {
            Hash = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            User = input.ReadString();
            break;
          }
          case 18: {
            Hash = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
