// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cardchain/cardchain/set_with_artwork.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cardchain.Cardchain {

  /// <summary>Holder for reflection information generated from cardchain/cardchain/set_with_artwork.proto</summary>
  public static partial class SetWithArtworkReflection {

    #region Descriptor
    /// <summary>File descriptor for cardchain/cardchain/set_with_artwork.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SetWithArtworkReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipjYXJkY2hhaW4vY2FyZGNoYWluL3NldF93aXRoX2FydHdvcmsucHJvdG8S",
            "E2NhcmRjaGFpbi5jYXJkY2hhaW4aHWNhcmRjaGFpbi9jYXJkY2hhaW4vc2V0",
            "LnByb3RvIlYKDlNldFdpdGhBcnR3b3JrEioKA3NldBgBIAEoCzIYLmNhcmRj",
            "aGFpbi5jYXJkY2hhaW4uU2V0UgNzZXQSGAoHYXJ0d29yaxgCIAEoDFIHYXJ0",
            "d29ya0LXAQoXY29tLmNhcmRjaGFpbi5jYXJkY2hhaW5CE1NldFdpdGhBcnR3",
            "b3JrUHJvdG9QAVo6Z2l0aHViLmNvbS9EZWNlbnRyYWxDYXJkZ2FtZS9jYXJk",
            "Y2hhaW4vY2FyZGNoYWluL2NhcmRjaGFpbqICA0NDWKoCE0NhcmRjaGFpbi5D",
            "YXJkY2hhaW7KAhNDYXJkY2hhaW5cQ2FyZGNoYWlu4gIfQ2FyZGNoYWluXENh",
            "cmRjaGFpblxHUEJNZXRhZGF0YeoCFENhcmRjaGFpbjo6Q2FyZGNoYWluYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Cardchain.Cardchain.SetReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Cardchain.Cardchain.SetWithArtwork), global::Cardchain.Cardchain.SetWithArtwork.Parser, new[]{ "Set", "Artwork" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SetWithArtwork : pb::IMessage<SetWithArtwork>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SetWithArtwork> _parser = new pb::MessageParser<SetWithArtwork>(() => new SetWithArtwork());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SetWithArtwork> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cardchain.Cardchain.SetWithArtworkReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetWithArtwork() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetWithArtwork(SetWithArtwork other) : this() {
      set_ = other.set_ != null ? other.set_.Clone() : null;
      artwork_ = other.artwork_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SetWithArtwork Clone() {
      return new SetWithArtwork(this);
    }

    /// <summary>Field number for the "set" field.</summary>
    public const int SetFieldNumber = 1;
    private global::Cardchain.Cardchain.Set set_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cardchain.Cardchain.Set Set {
      get { return set_; }
      set {
        set_ = value;
      }
    }

    /// <summary>Field number for the "artwork" field.</summary>
    public const int ArtworkFieldNumber = 2;
    private pb::ByteString artwork_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Artwork {
      get { return artwork_; }
      set {
        artwork_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SetWithArtwork);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SetWithArtwork other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Set, other.Set)) return false;
      if (Artwork != other.Artwork) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (set_ != null) hash ^= Set.GetHashCode();
      if (Artwork.Length != 0) hash ^= Artwork.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (set_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Set);
      }
      if (Artwork.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Artwork);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (set_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Set);
      }
      if (Artwork.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Artwork);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (set_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Set);
      }
      if (Artwork.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Artwork);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SetWithArtwork other) {
      if (other == null) {
        return;
      }
      if (other.set_ != null) {
        if (set_ == null) {
          Set = new global::Cardchain.Cardchain.Set();
        }
        Set.MergeFrom(other.Set);
      }
      if (other.Artwork.Length != 0) {
        Artwork = other.Artwork;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (set_ == null) {
              Set = new global::Cardchain.Cardchain.Set();
            }
            input.ReadMessage(Set);
            break;
          }
          case 18: {
            Artwork = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (set_ == null) {
              Set = new global::Cardchain.Cardchain.Set();
            }
            input.ReadMessage(Set);
            break;
          }
          case 18: {
            Artwork = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
