// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DecentralCardGame/cardchain/cardchain/match.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DecentralCardGame.Cardchain.Cardchain {

  /// <summary>Holder for reflection information generated from DecentralCardGame/cardchain/cardchain/match.proto</summary>
  public static partial class MatchReflection {

    #region Descriptor
    /// <summary>File descriptor for DecentralCardGame/cardchain/cardchain/match.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MatchReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFEZWNlbnRyYWxDYXJkR2FtZS9jYXJkY2hhaW4vY2FyZGNoYWluL21hdGNo",
            "LnByb3RvEiVEZWNlbnRyYWxDYXJkR2FtZS5jYXJkY2hhaW4uY2FyZGNoYWlu",
            "Gi5EZWNlbnRyYWxDYXJkR2FtZS9jYXJkY2hhaW4vY2FyZGNoYWluL3R4LnBy",
            "b3RvItMCCgVNYXRjaBIcCgl0aW1lc3RhbXAYASABKARSCXRpbWVzdGFtcBIa",
            "CghyZXBvcnRlchgCIAEoCVIIcmVwb3J0ZXISTAoHcGxheWVyQRgDIAEoCzIy",
            "LkRlY2VudHJhbENhcmRHYW1lLmNhcmRjaGFpbi5jYXJkY2hhaW4uTWF0Y2hQ",
            "bGF5ZXJSB3BsYXllckESTAoHcGxheWVyQhgEIAEoCzIyLkRlY2VudHJhbENh",
            "cmRHYW1lLmNhcmRjaGFpbi5jYXJkY2hhaW4uTWF0Y2hQbGF5ZXJSB3BsYXll",
            "ckISSAoHb3V0Y29tZRgHIAEoDjIuLkRlY2VudHJhbENhcmRHYW1lLmNhcmRj",
            "aGFpbi5jYXJkY2hhaW4uT3V0Y29tZVIHb3V0Y29tZRIqChBjb2luc0Rpc3Ry",
            "aWJ1dGVkGAogASgIUhBjb2luc0Rpc3RyaWJ1dGVkIqsBCgtNYXRjaFBsYXll",
            "chISCgRhZGRyGAEgASgJUgRhZGRyEiAKC3BsYXllZENhcmRzGAIgAygEUgtw",
            "bGF5ZWRDYXJkcxIcCgljb25maXJtZWQYAyABKAhSCWNvbmZpcm1lZBJICgdv",
            "dXRjb21lGAQgASgOMi4uRGVjZW50cmFsQ2FyZEdhbWUuY2FyZGNoYWluLmNh",
            "cmRjaGFpbi5PdXRjb21lUgdvdXRjb21lQqcCCiljb20uRGVjZW50cmFsQ2Fy",
            "ZEdhbWUuY2FyZGNoYWluLmNhcmRjaGFpbkIKTWF0Y2hQcm90b1ABWjhnaXRo",
            "dWIuY29tL0RlY2VudHJhbENhcmRHYW1lL0NhcmRjaGFpbi94L2NhcmRjaGFp",
            "bi90eXBlc6ICA0RDQ6oCJURlY2VudHJhbENhcmRHYW1lLkNhcmRjaGFpbi5D",
            "YXJkY2hhaW7KAiVEZWNlbnRyYWxDYXJkR2FtZVxDYXJkY2hhaW5cQ2FyZGNo",
            "YWlu4gIxRGVjZW50cmFsQ2FyZEdhbWVcQ2FyZGNoYWluXENhcmRjaGFpblxH",
            "UEJNZXRhZGF0YeoCJ0RlY2VudHJhbENhcmRHYW1lOjpDYXJkY2hhaW46OkNh",
            "cmRjaGFpbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DecentralCardGame.Cardchain.Cardchain.TxReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DecentralCardGame.Cardchain.Cardchain.Match), global::DecentralCardGame.Cardchain.Cardchain.Match.Parser, new[]{ "Timestamp", "Reporter", "PlayerA", "PlayerB", "Outcome", "CoinsDistributed" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer), global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer.Parser, new[]{ "Addr", "PlayedCards", "Confirmed", "Outcome" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Match : pb::IMessage<Match>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Match> _parser = new pb::MessageParser<Match>(() => new Match());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Match> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DecentralCardGame.Cardchain.Cardchain.MatchReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Match() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Match(Match other) : this() {
      timestamp_ = other.timestamp_;
      reporter_ = other.reporter_;
      playerA_ = other.playerA_ != null ? other.playerA_.Clone() : null;
      playerB_ = other.playerB_ != null ? other.playerB_.Clone() : null;
      outcome_ = other.outcome_;
      coinsDistributed_ = other.coinsDistributed_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Match Clone() {
      return new Match(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private ulong timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "reporter" field.</summary>
    public const int ReporterFieldNumber = 2;
    private string reporter_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Reporter {
      get { return reporter_; }
      set {
        reporter_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "playerA" field.</summary>
    public const int PlayerAFieldNumber = 3;
    private global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer playerA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer PlayerA {
      get { return playerA_; }
      set {
        playerA_ = value;
      }
    }

    /// <summary>Field number for the "playerB" field.</summary>
    public const int PlayerBFieldNumber = 4;
    private global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer playerB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer PlayerB {
      get { return playerB_; }
      set {
        playerB_ = value;
      }
    }

    /// <summary>Field number for the "outcome" field.</summary>
    public const int OutcomeFieldNumber = 7;
    private global::DecentralCardGame.Cardchain.Cardchain.Outcome outcome_ = global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DecentralCardGame.Cardchain.Cardchain.Outcome Outcome {
      get { return outcome_; }
      set {
        outcome_ = value;
      }
    }

    /// <summary>Field number for the "coinsDistributed" field.</summary>
    public const int CoinsDistributedFieldNumber = 10;
    private bool coinsDistributed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CoinsDistributed {
      get { return coinsDistributed_; }
      set {
        coinsDistributed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Match);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Match other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if (Reporter != other.Reporter) return false;
      if (!object.Equals(PlayerA, other.PlayerA)) return false;
      if (!object.Equals(PlayerB, other.PlayerB)) return false;
      if (Outcome != other.Outcome) return false;
      if (CoinsDistributed != other.CoinsDistributed) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      if (Reporter.Length != 0) hash ^= Reporter.GetHashCode();
      if (playerA_ != null) hash ^= PlayerA.GetHashCode();
      if (playerB_ != null) hash ^= PlayerB.GetHashCode();
      if (Outcome != global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon) hash ^= Outcome.GetHashCode();
      if (CoinsDistributed != false) hash ^= CoinsDistributed.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Timestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Timestamp);
      }
      if (Reporter.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Reporter);
      }
      if (playerA_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PlayerA);
      }
      if (playerB_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PlayerB);
      }
      if (Outcome != global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Outcome);
      }
      if (CoinsDistributed != false) {
        output.WriteRawTag(80);
        output.WriteBool(CoinsDistributed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Timestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Timestamp);
      }
      if (Reporter.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Reporter);
      }
      if (playerA_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PlayerA);
      }
      if (playerB_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PlayerB);
      }
      if (Outcome != global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Outcome);
      }
      if (CoinsDistributed != false) {
        output.WriteRawTag(80);
        output.WriteBool(CoinsDistributed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      if (Reporter.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Reporter);
      }
      if (playerA_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerA);
      }
      if (playerB_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerB);
      }
      if (Outcome != global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Outcome);
      }
      if (CoinsDistributed != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Match other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      if (other.Reporter.Length != 0) {
        Reporter = other.Reporter;
      }
      if (other.playerA_ != null) {
        if (playerA_ == null) {
          PlayerA = new global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer();
        }
        PlayerA.MergeFrom(other.PlayerA);
      }
      if (other.playerB_ != null) {
        if (playerB_ == null) {
          PlayerB = new global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer();
        }
        PlayerB.MergeFrom(other.PlayerB);
      }
      if (other.Outcome != global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon) {
        Outcome = other.Outcome;
      }
      if (other.CoinsDistributed != false) {
        CoinsDistributed = other.CoinsDistributed;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 18: {
            Reporter = input.ReadString();
            break;
          }
          case 26: {
            if (playerA_ == null) {
              PlayerA = new global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer();
            }
            input.ReadMessage(PlayerA);
            break;
          }
          case 34: {
            if (playerB_ == null) {
              PlayerB = new global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer();
            }
            input.ReadMessage(PlayerB);
            break;
          }
          case 56: {
            Outcome = (global::DecentralCardGame.Cardchain.Cardchain.Outcome) input.ReadEnum();
            break;
          }
          case 80: {
            CoinsDistributed = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 18: {
            Reporter = input.ReadString();
            break;
          }
          case 26: {
            if (playerA_ == null) {
              PlayerA = new global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer();
            }
            input.ReadMessage(PlayerA);
            break;
          }
          case 34: {
            if (playerB_ == null) {
              PlayerB = new global::DecentralCardGame.Cardchain.Cardchain.MatchPlayer();
            }
            input.ReadMessage(PlayerB);
            break;
          }
          case 56: {
            Outcome = (global::DecentralCardGame.Cardchain.Cardchain.Outcome) input.ReadEnum();
            break;
          }
          case 80: {
            CoinsDistributed = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MatchPlayer : pb::IMessage<MatchPlayer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MatchPlayer> _parser = new pb::MessageParser<MatchPlayer>(() => new MatchPlayer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MatchPlayer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DecentralCardGame.Cardchain.Cardchain.MatchReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchPlayer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchPlayer(MatchPlayer other) : this() {
      addr_ = other.addr_;
      playedCards_ = other.playedCards_.Clone();
      confirmed_ = other.confirmed_;
      outcome_ = other.outcome_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchPlayer Clone() {
      return new MatchPlayer(this);
    }

    /// <summary>Field number for the "addr" field.</summary>
    public const int AddrFieldNumber = 1;
    private string addr_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Addr {
      get { return addr_; }
      set {
        addr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "playedCards" field.</summary>
    public const int PlayedCardsFieldNumber = 2;
    private static readonly pb::FieldCodec<ulong> _repeated_playedCards_codec
        = pb::FieldCodec.ForUInt64(18);
    private readonly pbc::RepeatedField<ulong> playedCards_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<ulong> PlayedCards {
      get { return playedCards_; }
    }

    /// <summary>Field number for the "confirmed" field.</summary>
    public const int ConfirmedFieldNumber = 3;
    private bool confirmed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Confirmed {
      get { return confirmed_; }
      set {
        confirmed_ = value;
      }
    }

    /// <summary>Field number for the "outcome" field.</summary>
    public const int OutcomeFieldNumber = 4;
    private global::DecentralCardGame.Cardchain.Cardchain.Outcome outcome_ = global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DecentralCardGame.Cardchain.Cardchain.Outcome Outcome {
      get { return outcome_; }
      set {
        outcome_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MatchPlayer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MatchPlayer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Addr != other.Addr) return false;
      if(!playedCards_.Equals(other.playedCards_)) return false;
      if (Confirmed != other.Confirmed) return false;
      if (Outcome != other.Outcome) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Addr.Length != 0) hash ^= Addr.GetHashCode();
      hash ^= playedCards_.GetHashCode();
      if (Confirmed != false) hash ^= Confirmed.GetHashCode();
      if (Outcome != global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon) hash ^= Outcome.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Addr.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Addr);
      }
      playedCards_.WriteTo(output, _repeated_playedCards_codec);
      if (Confirmed != false) {
        output.WriteRawTag(24);
        output.WriteBool(Confirmed);
      }
      if (Outcome != global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Outcome);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Addr.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Addr);
      }
      playedCards_.WriteTo(ref output, _repeated_playedCards_codec);
      if (Confirmed != false) {
        output.WriteRawTag(24);
        output.WriteBool(Confirmed);
      }
      if (Outcome != global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Outcome);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Addr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Addr);
      }
      size += playedCards_.CalculateSize(_repeated_playedCards_codec);
      if (Confirmed != false) {
        size += 1 + 1;
      }
      if (Outcome != global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Outcome);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MatchPlayer other) {
      if (other == null) {
        return;
      }
      if (other.Addr.Length != 0) {
        Addr = other.Addr;
      }
      playedCards_.Add(other.playedCards_);
      if (other.Confirmed != false) {
        Confirmed = other.Confirmed;
      }
      if (other.Outcome != global::DecentralCardGame.Cardchain.Cardchain.Outcome.Awon) {
        Outcome = other.Outcome;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Addr = input.ReadString();
            break;
          }
          case 18:
          case 16: {
            playedCards_.AddEntriesFrom(input, _repeated_playedCards_codec);
            break;
          }
          case 24: {
            Confirmed = input.ReadBool();
            break;
          }
          case 32: {
            Outcome = (global::DecentralCardGame.Cardchain.Cardchain.Outcome) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Addr = input.ReadString();
            break;
          }
          case 18:
          case 16: {
            playedCards_.AddEntriesFrom(ref input, _repeated_playedCards_codec);
            break;
          }
          case 24: {
            Confirmed = input.ReadBool();
            break;
          }
          case 32: {
            Outcome = (global::DecentralCardGame.Cardchain.Cardchain.Outcome) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
