// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DecentralCardGame/cardchain/cardchain/voting_results.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DecentralCardGame.Cardchain.Cardchain {

  /// <summary>Holder for reflection information generated from DecentralCardGame/cardchain/cardchain/voting_results.proto</summary>
  public static partial class VotingResultsReflection {

    #region Descriptor
    /// <summary>File descriptor for DecentralCardGame/cardchain/cardchain/voting_results.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VotingResultsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjpEZWNlbnRyYWxDYXJkR2FtZS9jYXJkY2hhaW4vY2FyZGNoYWluL3ZvdGlu",
            "Z19yZXN1bHRzLnByb3RvEiVEZWNlbnRyYWxDYXJkR2FtZS5jYXJkY2hhaW4u",
            "Y2FyZGNoYWluGjlEZWNlbnRyYWxDYXJkR2FtZS9jYXJkY2hhaW4vY2FyZGNo",
            "YWluL3ZvdGluZ19yZXN1bHQucHJvdG8i+AIKDVZvdGluZ1Jlc3VsdHMSHgoK",
            "dG90YWxWb3RlcxgBIAEoBFIKdG90YWxWb3RlcxIyChR0b3RhbEZhaXJFbm91",
            "Z2hWb3RlcxgCIAEoBFIUdG90YWxGYWlyRW5vdWdoVm90ZXMSNAoVdG90YWxP",
            "dmVycG93ZXJlZFZvdGVzGAMgASgEUhV0b3RhbE92ZXJwb3dlcmVkVm90ZXMS",
            "NgoWdG90YWxVbmRlcnBvd2VyZWRWb3RlcxgEIAEoBFIWdG90YWxVbmRlcnBv",
            "d2VyZWRWb3RlcxI4Chd0b3RhbEluYXBwcm9wcmlhdGVWb3RlcxgFIAEoBFIX",
            "dG90YWxJbmFwcHJvcHJpYXRlVm90ZXMSVQoLY2FyZFJlc3VsdHMYBiADKAsy",
            "My5EZWNlbnRyYWxDYXJkR2FtZS5jYXJkY2hhaW4uY2FyZGNoYWluLlZvdGlu",
            "Z1Jlc3VsdFILY2FyZFJlc3VsdHMSFAoFbm90ZXMYByABKAlSBW5vdGVzQq8C",
            "Ciljb20uRGVjZW50cmFsQ2FyZEdhbWUuY2FyZGNoYWluLmNhcmRjaGFpbkIS",
            "Vm90aW5nUmVzdWx0c1Byb3RvUAFaOGdpdGh1Yi5jb20vRGVjZW50cmFsQ2Fy",
            "ZEdhbWUvQ2FyZGNoYWluL3gvY2FyZGNoYWluL3R5cGVzogIDRENDqgIlRGVj",
            "ZW50cmFsQ2FyZEdhbWUuQ2FyZGNoYWluLkNhcmRjaGFpbsoCJURlY2VudHJh",
            "bENhcmRHYW1lXENhcmRjaGFpblxDYXJkY2hhaW7iAjFEZWNlbnRyYWxDYXJk",
            "R2FtZVxDYXJkY2hhaW5cQ2FyZGNoYWluXEdQQk1ldGFkYXRh6gInRGVjZW50",
            "cmFsQ2FyZEdhbWU6OkNhcmRjaGFpbjo6Q2FyZGNoYWluYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DecentralCardGame.Cardchain.Cardchain.VotingResultReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DecentralCardGame.Cardchain.Cardchain.VotingResults), global::DecentralCardGame.Cardchain.Cardchain.VotingResults.Parser, new[]{ "TotalVotes", "TotalFairEnoughVotes", "TotalOverpoweredVotes", "TotalUnderpoweredVotes", "TotalInappropriateVotes", "CardResults", "Notes" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class VotingResults : pb::IMessage<VotingResults>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VotingResults> _parser = new pb::MessageParser<VotingResults>(() => new VotingResults());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VotingResults> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DecentralCardGame.Cardchain.Cardchain.VotingResultsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VotingResults() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VotingResults(VotingResults other) : this() {
      totalVotes_ = other.totalVotes_;
      totalFairEnoughVotes_ = other.totalFairEnoughVotes_;
      totalOverpoweredVotes_ = other.totalOverpoweredVotes_;
      totalUnderpoweredVotes_ = other.totalUnderpoweredVotes_;
      totalInappropriateVotes_ = other.totalInappropriateVotes_;
      cardResults_ = other.cardResults_.Clone();
      notes_ = other.notes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VotingResults Clone() {
      return new VotingResults(this);
    }

    /// <summary>Field number for the "totalVotes" field.</summary>
    public const int TotalVotesFieldNumber = 1;
    private ulong totalVotes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TotalVotes {
      get { return totalVotes_; }
      set {
        totalVotes_ = value;
      }
    }

    /// <summary>Field number for the "totalFairEnoughVotes" field.</summary>
    public const int TotalFairEnoughVotesFieldNumber = 2;
    private ulong totalFairEnoughVotes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TotalFairEnoughVotes {
      get { return totalFairEnoughVotes_; }
      set {
        totalFairEnoughVotes_ = value;
      }
    }

    /// <summary>Field number for the "totalOverpoweredVotes" field.</summary>
    public const int TotalOverpoweredVotesFieldNumber = 3;
    private ulong totalOverpoweredVotes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TotalOverpoweredVotes {
      get { return totalOverpoweredVotes_; }
      set {
        totalOverpoweredVotes_ = value;
      }
    }

    /// <summary>Field number for the "totalUnderpoweredVotes" field.</summary>
    public const int TotalUnderpoweredVotesFieldNumber = 4;
    private ulong totalUnderpoweredVotes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TotalUnderpoweredVotes {
      get { return totalUnderpoweredVotes_; }
      set {
        totalUnderpoweredVotes_ = value;
      }
    }

    /// <summary>Field number for the "totalInappropriateVotes" field.</summary>
    public const int TotalInappropriateVotesFieldNumber = 5;
    private ulong totalInappropriateVotes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TotalInappropriateVotes {
      get { return totalInappropriateVotes_; }
      set {
        totalInappropriateVotes_ = value;
      }
    }

    /// <summary>Field number for the "cardResults" field.</summary>
    public const int CardResultsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::DecentralCardGame.Cardchain.Cardchain.VotingResult> _repeated_cardResults_codec
        = pb::FieldCodec.ForMessage(50, global::DecentralCardGame.Cardchain.Cardchain.VotingResult.Parser);
    private readonly pbc::RepeatedField<global::DecentralCardGame.Cardchain.Cardchain.VotingResult> cardResults_ = new pbc::RepeatedField<global::DecentralCardGame.Cardchain.Cardchain.VotingResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DecentralCardGame.Cardchain.Cardchain.VotingResult> CardResults {
      get { return cardResults_; }
    }

    /// <summary>Field number for the "notes" field.</summary>
    public const int NotesFieldNumber = 7;
    private string notes_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Notes {
      get { return notes_; }
      set {
        notes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VotingResults);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VotingResults other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TotalVotes != other.TotalVotes) return false;
      if (TotalFairEnoughVotes != other.TotalFairEnoughVotes) return false;
      if (TotalOverpoweredVotes != other.TotalOverpoweredVotes) return false;
      if (TotalUnderpoweredVotes != other.TotalUnderpoweredVotes) return false;
      if (TotalInappropriateVotes != other.TotalInappropriateVotes) return false;
      if(!cardResults_.Equals(other.cardResults_)) return false;
      if (Notes != other.Notes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TotalVotes != 0UL) hash ^= TotalVotes.GetHashCode();
      if (TotalFairEnoughVotes != 0UL) hash ^= TotalFairEnoughVotes.GetHashCode();
      if (TotalOverpoweredVotes != 0UL) hash ^= TotalOverpoweredVotes.GetHashCode();
      if (TotalUnderpoweredVotes != 0UL) hash ^= TotalUnderpoweredVotes.GetHashCode();
      if (TotalInappropriateVotes != 0UL) hash ^= TotalInappropriateVotes.GetHashCode();
      hash ^= cardResults_.GetHashCode();
      if (Notes.Length != 0) hash ^= Notes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TotalVotes != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TotalVotes);
      }
      if (TotalFairEnoughVotes != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(TotalFairEnoughVotes);
      }
      if (TotalOverpoweredVotes != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(TotalOverpoweredVotes);
      }
      if (TotalUnderpoweredVotes != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(TotalUnderpoweredVotes);
      }
      if (TotalInappropriateVotes != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(TotalInappropriateVotes);
      }
      cardResults_.WriteTo(output, _repeated_cardResults_codec);
      if (Notes.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Notes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TotalVotes != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TotalVotes);
      }
      if (TotalFairEnoughVotes != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(TotalFairEnoughVotes);
      }
      if (TotalOverpoweredVotes != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(TotalOverpoweredVotes);
      }
      if (TotalUnderpoweredVotes != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(TotalUnderpoweredVotes);
      }
      if (TotalInappropriateVotes != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(TotalInappropriateVotes);
      }
      cardResults_.WriteTo(ref output, _repeated_cardResults_codec);
      if (Notes.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Notes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TotalVotes != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TotalVotes);
      }
      if (TotalFairEnoughVotes != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TotalFairEnoughVotes);
      }
      if (TotalOverpoweredVotes != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TotalOverpoweredVotes);
      }
      if (TotalUnderpoweredVotes != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TotalUnderpoweredVotes);
      }
      if (TotalInappropriateVotes != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TotalInappropriateVotes);
      }
      size += cardResults_.CalculateSize(_repeated_cardResults_codec);
      if (Notes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Notes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VotingResults other) {
      if (other == null) {
        return;
      }
      if (other.TotalVotes != 0UL) {
        TotalVotes = other.TotalVotes;
      }
      if (other.TotalFairEnoughVotes != 0UL) {
        TotalFairEnoughVotes = other.TotalFairEnoughVotes;
      }
      if (other.TotalOverpoweredVotes != 0UL) {
        TotalOverpoweredVotes = other.TotalOverpoweredVotes;
      }
      if (other.TotalUnderpoweredVotes != 0UL) {
        TotalUnderpoweredVotes = other.TotalUnderpoweredVotes;
      }
      if (other.TotalInappropriateVotes != 0UL) {
        TotalInappropriateVotes = other.TotalInappropriateVotes;
      }
      cardResults_.Add(other.cardResults_);
      if (other.Notes.Length != 0) {
        Notes = other.Notes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TotalVotes = input.ReadUInt64();
            break;
          }
          case 16: {
            TotalFairEnoughVotes = input.ReadUInt64();
            break;
          }
          case 24: {
            TotalOverpoweredVotes = input.ReadUInt64();
            break;
          }
          case 32: {
            TotalUnderpoweredVotes = input.ReadUInt64();
            break;
          }
          case 40: {
            TotalInappropriateVotes = input.ReadUInt64();
            break;
          }
          case 50: {
            cardResults_.AddEntriesFrom(input, _repeated_cardResults_codec);
            break;
          }
          case 58: {
            Notes = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TotalVotes = input.ReadUInt64();
            break;
          }
          case 16: {
            TotalFairEnoughVotes = input.ReadUInt64();
            break;
          }
          case 24: {
            TotalOverpoweredVotes = input.ReadUInt64();
            break;
          }
          case 32: {
            TotalUnderpoweredVotes = input.ReadUInt64();
            break;
          }
          case 40: {
            TotalInappropriateVotes = input.ReadUInt64();
            break;
          }
          case 50: {
            cardResults_.AddEntriesFrom(ref input, _repeated_cardResults_codec);
            break;
          }
          case 58: {
            Notes = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
