// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cardchain/featureflag/tx.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DecentralCardGame.Cardchain.Featureflag {

  /// <summary>Holder for reflection information generated from cardchain/featureflag/tx.proto</summary>
  public static partial class TxReflection {

    #region Descriptor
    /// <summary>File descriptor for cardchain/featureflag/tx.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TxReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5jYXJkY2hhaW4vZmVhdHVyZWZsYWcvdHgucHJvdG8SJ0RlY2VudHJhbENh",
            "cmRHYW1lLmNhcmRjaGFpbi5mZWF0dXJlZmxhZzIFCgNNc2dCsgIKK2NvbS5E",
            "ZWNlbnRyYWxDYXJkR2FtZS5jYXJkY2hhaW4uZmVhdHVyZWZsYWdCB1R4UHJv",
            "dG9QAVo8Z2l0aHViLmNvbS9EZWNlbnRyYWxDYXJkZ2FtZS9DYXJkY2hhaW4v",
            "Y2FyZGNoYWluL2ZlYXR1cmVmbGFnogIDRENGqgInRGVjZW50cmFsQ2FyZEdh",
            "bWUuQ2FyZGNoYWluLkZlYXR1cmVmbGFnygInRGVjZW50cmFsQ2FyZEdhbWVc",
            "Q2FyZGNoYWluXEZlYXR1cmVmbGFn4gIzRGVjZW50cmFsQ2FyZEdhbWVcQ2Fy",
            "ZGNoYWluXEZlYXR1cmVmbGFnXEdQQk1ldGFkYXRh6gIpRGVjZW50cmFsQ2Fy",
            "ZEdhbWU6OkNhcmRjaGFpbjo6RmVhdHVyZWZsYWdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
